import './globals.css'
import InputBarProvider from '@/hooks/InputBarContext'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <InputBarProvider>{children}</InputBarProvider>
      </body>
    </html>
  )
}
