import "./globals.css";
import InputBarProvider from "@/hooks/InputBarContext";
import ThemeProvider from "@/hooks/ThemeContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <InputBarProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </InputBarProvider>
      </body>
    </html>
  );
}
